# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15.1

ARG UPSTREAM_URL="https://api.github.com/repos/go-gitea/gitea/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG BINARY_JQ=".assets[] | select(.name | test(\"^gitea-.*-freebsd14-amd64$\")) | .browser_download_url"

FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="FreeBSD-ssh devel/git-lfs shells/bash"
ARG HEALTHCHECK_ENDPOINT="http://localhost:3000/api/healthz"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Gitea" \
      org.opencontainers.image.description="Lightweight self-hosted Git service — a community managed fork of Gogs written in Go." \
      org.opencontainers.image.source="https://github.com/daemonless/gitea" \
      org.opencontainers.image.url="https://about.gitea.com/" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Infrastructure" \
      io.daemonless.port="3000" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}"

# Update to latest patch level
RUN pkg update -r FreeBSD-base && \
    pkg upgrade -y -r FreeBSD-base && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Install run dependencies
RUN pkg update && \
    pkg install -y \
    ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Create required directories
RUN mkdir -m 0755 -p /app /config/bin /config/data /config/custom/conf /config/repos /config/log /config/lfs /config/tmp && \
    chown -R bsd:bsd /app /config

ARG UPSTREAM_URL
ARG UPSTREAM_JQ
ARG BINARY_JQ

# Download Gitea binary from GitHub Releases
RUN fetch -qo /tmp/latest.json "${UPSTREAM_URL}" && \
    BINARY_URL=$(jq -r "${BINARY_JQ}" /tmp/latest.json) && \
    echo "Downloading Gitea from ${BINARY_URL}..." && \
    fetch -qo /usr/local/sbin/gitea "${BINARY_URL}" && \
    chmod 755 /usr/local/sbin/gitea && \
    chown bsd:bsd /usr/local/sbin/gitea && \
    VERSION=$(jq -r "${UPSTREAM_JQ}" /tmp/latest.json) && \
    echo "${VERSION}" | sed -n 's/^v\(.*\)$/\1/p' > /app/version && \
    rm -f /tmp/latest.json

# Copy service definition and init scripts
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 3000 22

# --- Volumes (Injected by Generator) ---
VOLUME /config