icon: ':simple-gitea:'

cit:
  mode: screenshot
  port: 3000
  ssim_threshold: 0.85
  ready: "Starting new Web server"

build:
  variants:
    - tag: latest
      containerfile: Containerfile
      default: true
    - tag: latest-latest
      containerfile: Containerfile
      args:
        BASE_VERSION: "15-latest"
    - tag: pkg
      containerfile: Containerfile.pkg
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
